version: '3.4'
services:
    
  app:
    build: ../app
    restart: always
    ports:
     - "8888:8888"
    depends_on:
      - weaviate
    env_file:
      - .env

  weaviate:
    image: semitechnologies/weaviate:1.20.3
    restart: always
    ports:
     - "8080:8080"
    env_file:
      - .env
